state_publisher_node:
  ros__parameters:
    test: 0

line_follower_node:
  ros__parameters:
    max_steer_angle: 30.0
    line_inverted: True
    button_toggle: True

utility_service_node:
  ros__parameters:
    test: 0

teleop_node:
  ros__parameters:
    timeout_sec: 2.0
    max_steer_angle: 30.0