robot_hat_node:
  ros__parameters:
    max_motor_percent: 100.0
    motor_left_id: 1
    motor_right_id: 2
    motor_left_reversed: False
    motor_right_reversed: True
    servo_channels: ["P0"]
    servo_correction: [10.0]
    ultrasonic_sensor: True
    ultrasonic_pins: ["D2", "D3"]
    grayscale_sensor: True
    grayscale_pins: ["A0", "A1", "A2"]
    grayscale_calibration: [1495, 1481, 1457, 1429, 1378, 1067]